<?php $helper = $this->getHelper('DonateHelper');?>
<script src="assets/js/form/pin.js"></script>
<div id="pin-content" tokens="<?php echo $this->data[0][0]['pin'];?>">
	<div class="row">
		<div class="col-xs-3">
			<div class="xe-widget xe-progress-counter xe-progress-counter-pink">
				<div class="xe-background">
					<i class="linecons-heart"></i>
				</div>
				<div class="xe-upper">
					<div class="xe-icon">
						<i class="linecons-heart"></i>
					</div>
					<div class="xe-label">
						<span>Tokens</span> <strong class="num"><?php echo $this->data[0][0]['pin'];?></strong>
					</div>
				</div>
				<div class="xe-progress">
					<span style="width: 50%;" class="xe-progress-fill" data-fill-from="0"
						data-fill-to="100" data-fill-unit="%" data-fill-property="width"
						data-fill-duration="2" data-fill-easing="true"></span>
				</div>

				<div class="xe-lower"></div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-6">
		<button type="button" id= "request_pin"  class="btn btn-turquoise">Request Tokens</button>
		<button type="button" id="send_pin" class="btn btn-turquoise">Send Tokens</button>
		</div>
	</div>


	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Tokens History</h3>
		</div>
		<div class="panel-body">
			<div id="example-2_wrapper"
				class="dataTables_wrapper form-inline dt-bootstrap no-footer">
				<table class="table table-bordered table-striped dataTable no-footer"
					id="example-2" role="grid" aria-describedby="example-2_info">
					<thead>
						<tr role="row">
							<th>No</th>
							<th>Amount (Tokens)</th>
							<th>Balance (Tokens)</th>
							<th>Tranfer</th>
							<th>Date</th>
							<th>Description</th>
						</tr>
					</thead>
					<tbody class="middle-align">
						<?php foreach ($this->data[1] as $index => $row) {?>
						<tr role="row">
							<td><?php echo ++$index;?></td>
							<td><?php echo $helper->prefixPin($row['type']) . $row['pin_tranfer'];?></td>
							<td><?php echo $row['balance_pin'];?></td>
							<td><?php echo $row['tranfer_user_name'];?></td>
							<td><?php echo $row['create_date'];?></td>
							<td><?php echo $row['name_tranfer'];?></td>
						</tr>
						<?php }?>

					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>