<table class="table table-bordered table-striped dataTable no-footer"
	id="example-2" role="grid" aria-describedby="example-2_info">
	<thead>
		<tr role="row">
			<th style="width:50px">No</th>
			<th style="width:150px">FROM</th>
			<th>Content</th>
			<th style="width:100px">Status</th>
			<th style="width:150px"></th>
		</tr>
	</thead>
	<tbody class="middle-align">
		<?php foreach ($this->arrmsg as $key => $row){?>
		<tr role="row">
			<td><?php echo $key+1;?></td>
			<td><?php echo $row['user_name'];?></td>
			<td><?php echo $row['msg_content'];?></td>
			<td></td>
			<td>
				<a class="btn btn-info btn-sm btn-icon icon-left"
					href="/master/message/create/msg_id/<?php echo $row['msg_id'];?>">Edit</a>
				<a msg_id="<?php echo $row['msg_id']?>" class="btn btn-red btn-sm btn-icon icon-left btn-delete">Delete</a>
			</td>
		</tr>
		<?php }?>
	</tbody>
</table>
<div class="row">
	<div class="col-xs-12">
		<div class="dataTables_paginate paging_simple_numbers pull-right"
			id="example-2_paginate">
			<?php echo $this->paging;?>
		</div>
	</div>
</div>