<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Create Withdraw</h3>
		<div class="panel-options">
			<a href="#" data-toggle="panel"> <span class="collapse-icon"></span>
				<span class="expand-icon"></span>
			</a>
		</div>
	</div>
	<div class="panel-body">
		<div class="form-group col-xs-12">
			<label class="col-xs-3 control-label required" for="field-1">Withdrawable</label>
			<div class="col-xs-6"><?php echo $this->data['withdrawable']?> <i class="fa fa-btc" aria-hidden="true"></i></div>
		</div>
<!-- 		<div class="form-group col-xs-12"> -->
<!-- 			<label class="col-xs-3 control-label required" for="field-1">FEE</label> -->
<!-- 			<div class="col-xs-6"><?php //echo BLC::FEE;?> <i class="fa fa-btc" aria-hidden="true"></i></div>-->
<!-- 		</div> -->
		<div class="form-group col-xs-12">
			<button <?php if($this->data['withdrawable'] == 0){ echo 'disabled="disabled"';}?> id="create" class="btn btn-info">Create</button>
		</div>
	</div>
</div>