<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Add</h3>
		<div class="panel-options">
			<a href="#" data-toggle="panel"> <span class="collapse-icon"></span>
				<span class="expand-icon"></span>
			</a>
		</div>
	</div>
	<div class="panel-body">

		<div class="form-group col-xs-12">
			<label class="col-xs-3 control-label required" for="field-1">Parent User</label>
			<div class="col-xs-6">
				<input type="text" class="form-control required" id="parent_user" >
			</div>
		</div>

		<div class="form-group col-xs-12">
			<label class="col-xs-3 control-label required" for="field-1">Child User</label>
			<div class="col-xs-6">
				<select class="form-control required" id="child_user">
					<?php foreach ($this->data as $row) {?>
						<option value="<?php echo $row['user_id'];?>">
							<?php echo $row['user_name'];?>
						</option>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="form-group col-xs-12">
			<button id="add" class="btn btn-info">Add to tree</button>
		</div>
	</div>
</div>