<script src="assets/js/form/referral.js?<?php echo time();?>"></script>
<div id="referral-content">
<!-- 	<div class="row"> -->
<!-- 		<div class="col-xs-6"> -->
<!-- 			<button type="button" id= "btn_add_to_tree"  class="btn btn-turquoise">Add To Tree</button> -->
<!-- 		</div> -->
<!-- 	</div> -->
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">List of referral</h3>
		</div>
		<div class="panel-body">
			<div id="example-2_wrapper"
				class="dataTables_wrapper form-inline dt-bootstrap no-footer">
				<table class="table table-bordered table-striped dataTable no-footer"
					id="example-2" role="grid" aria-describedby="example-2_info">
					<thead>
						<tr role="row">
							<th>No</th>
							<th>User name</th>
							<th>Level</th>
							<th>Email</th>
							<th>Phone</th>
							<th>Date create</th>
							<th>Status</th>
						</tr>
					</thead>
					<tbody class="middle-align">
						<?php foreach ($this->rows as $index => $row) {?>
						<tr role="row">
							<td><?php echo ++$index;?></td>
							<td><?php echo $row['user_name'];?></td>
							<td><?php echo $row['rank_name'];?></td>
							<td><?php echo $row['email'];?></td>
							<td><?php echo $row['phone'];?></td>
							<td><?php echo $row['create_date'];?></td>
							<td><?php echo $row['status_name'];?></td>
						</tr>
						<?php }?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>