<style>
.name-error {
	display: block;
}
</style>
<script src="assets/js/form/admin.js?<?php echo time();?>"></script>
<div id="wallet-admin" style="position: relative;">
	<div class="row">
		<div class="col-xs-4">
			<div class="xe-widget xe-progress-counter xe-progress-counter-pink" data-count=".num" data-from="0" data-to="<?php echo $this->balance;?>" data-duration="2">
				<div class="xe-background">
					<i class="linecons-money"></i>
				</div>
				<div class="xe-upper">
					<div class="xe-icon">
						<i class="linecons-money"></i>
					</div>
					<div class="xe-label">
						<strong class="num"><?php echo $this->balance;?> </strong> <i class="fa fa-btc" aria-hidden="true"></i>
					</div>
				</div>
				<div class="xe-progress">
					<span class="xe-progress-fill" data-fill-from="0" data-fill-to="100" data-fill-unit="%" data-fill-property="width" data-fill-duration="2" data-fill-easing="true" style="width: 100%;"></span>
				</div>
				<div class="xe-lower">
					<strong>Admin Wallet</strong>
				</div>

			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Receive Form</h3>
					<div class="panel-options">
						<a href="#" data-toggle="panel"> <span class="collapse-icon">–</span> <span class="expand-icon">+</span>
						</a> <a href="#" data-toggle="remove"> × </a>
					</div>
				</div>
				<div class="panel-body">

					<form role="form" class="form-inline">

						<div class="form-group">
							<input id="nb_bit" class="form-control" size="30" placeholder="Number of bit" type="text" />
						</div>

						<div class="form-group">
							<button id="receive" type="button" class="btn btn-secondary btn-single">Receive</button>
						</div>

					</form>

				</div>
			</div>

		</div>
	</div>

</div>