<?php $news = $this->arrnews;?>
<input type="hidden" value="<?php echo isset($news['news_id'])? $news['news_id']:'';?>" id="news_id" />
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Create News</h3>
				<div class="panel-options">
					<a href="#" data-toggle="panel"> <span class="collapse-icon"></span>
						<span class="expand-icon"></span>
					</a>
				</div>
			</div>
			<div class="panel-body">
				<div role="form" class="form-horizontal">
					<div class="form-group">
						<label class="col-xs-3 control-label" for="image">Image</label>
						<div class="col-xs-6">
							<div class="input-group input-group-minimal">
								<input type="text" class="form-control" value="<?php echo isset($news['image'])? $news['image']:'';?>" readonly 
									id="image" onclick="BrowseServer();">
								<span class="input-group-btn">
									<button id="btn-upload" class="btn btn-purple" type="button">Upload image</button>
								</span>
								
							</div>
							<div class="form-group" style="text-align: right;padding-top:10px;padding-right:16px">
								<button id="btn-del-image" class="btn btn-red">Delete image</button>
							</div>
						</div>
						<div class="">
							<img id="news_image" src="<?php echo isset($news['image'])? $news['image']:'';?>" style="width:200px;height:200px" />
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-3 control-label" for="title">Title</label>
						<div class="col-xs-9">
							<input type="text" value="<?php echo isset($news['title'])? $news['title']:'';?>" class="form-control required" id="title">
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-3 control-label" for="description">Description</label>
						<div class="col-xs-9">
							<textarea class="form-control required" cols="5" rows="10" id="description"><?php echo isset($news['description'])? $news['description']:'';?></textarea>
						</div>
					</div>
					<div class="form-group" style="text-align: center">
						<button id="btn-save" class="btn btn-info">Save</button>
						<button id="btn-cancel" class="btn btn-red">Cancel</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script> var host_name='<?php echo $this->serverUrl();?>';</script>
<script type="text/javascript" src="/assets/js/plugin/ckfinder/ckfinder.js"></script>
<script type="text/javascript" src="/assets/js/plugin/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/assets/js/form/news.js?<?php echo time();?>"></script>