<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">List news</h3>
		<div class="panel-options">
			<a href="/master/news/create"><button class="btn btn-red">Create news</button></a>
		</div>
	</div>
	<div class="panel-body">
		<div id="example-2_wrapper"
			class="dataTables_wrapper form-inline dt-bootstrap no-footer">
			<div class="row">
				<div class="col-xs-6">
					<div class="dataTables_length">
						<label>Show 
						<select id="page_size" aria-controls="example-1" class="form-control input-sm">
								<option value="10">10</option>
								<option value="50">50</option>
								<option value="100">100</option>
						</select> entries
						</label>
					</div>
				</div>
				<div class="col-xs-6">
					<div id="example-1_filter" class="dataTables_filter pull-right">
						<label>Search:<input id="txt-search" type="search" class="form-control input-sm"
							placeholder="" aria-controls="example-1"></label>
					</div>
				</div>
			</div>
			<div id="display-result">
				<table class="table table-bordered table-striped dataTable no-footer"
					id="example-2" role="grid" aria-describedby="example-2_info">
					<thead>
						<tr role="row">
							<th style="width:50px">No</th>
							<th style="width:100px">Image</th>
							<th>News</th>
							<th style="width:200px">Date create</th>
							<th style="width:150px"></th>
						</tr>
					</thead>
					<tbody class="middle-align">
						<?php foreach ($this->arrnews as $key => $row){?>
						<tr role="row">
							<td><?php echo $key+1;?></td>
							<td>
								<img src="<?php echo $row['image'];?>" style="width:50px; height: 50px" />
							</td>
							<td><?php echo $row['title'];?></td>
							<td><?php echo $row['create_date'];?></td>
							<td>
								<a class="btn btn-info btn-sm btn-icon icon-left" 
									href="/master/news/create/news_id/<?php echo $row['news_id'];?>">Edit</a>
								<a news_id="<?php echo $row['news_id'];?>" class="btn btn-red btn-sm btn-icon icon-left btn-delete" <?php echo $row['news_id'];?>">Delete</a>
							</td>
						</tr>
						<?php }?>
					</tbody>
				</table>
				<div class="row">
					<div class="col-xs-12">
						<div class="dataTables_paginate paging_simple_numbers pull-right"
							id="example-2_paginate">
							<?php echo $this->paging;?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/assets/js/form/news.js?<?php echo time();?>"></script>