<table class="table table-bordered table-striped dataTable no-footer"
	id="example-2" role="grid" aria-describedby="example-2_info">
	<thead>
		<tr role="row">
			<th style="width:50px">No</th>
			<th style="width:100px">Image</th>
			<th>News</th>
			<th style="width:200px">Date create</th>
			<th style="width:150px"></th>
		</tr>
	</thead>
	<tbody class="middle-align">
		<?php foreach ($this->arrnews as $key => $row){?>
		<tr role="row">
			<td><?php echo $key+1;?></td>
			<td>
				<img src="<?php echo $row['image'];?>" style="width:50px; height: 50px" />
			</td>
			<td><?php echo $row['title'];?></td>
			<td><?php echo $row['create_date'];?></td>
			<td>
				<a class="btn btn-info btn-sm btn-icon icon-left" 
					href="/master/news/create/news_id/<?php echo $row['news_id'];?>">Edit</a>
				<a news_id="<?php echo $row['news_id'];?>" class="btn btn-red btn-sm btn-icon icon-left btn-delete" <?php echo $row['news_id'];?>">Delete</a>
			</td>
		</tr>
		<?php }?>
	</tbody>
</table>
<div class="row">
	<div class="col-xs-12">
		<div class="dataTables_paginate paging_simple_numbers pull-right"
			id="example-2_paginate">
			<?php echo $this->paging;?>
		</div>
	</div>
</div>