<?php echo $this->doctype(); ?>
<html lang="ja">
	<head>
		<title><?php echo "BTCCLUB - " . $this->title;?></title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">

		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="description" content="Admin Panel" />
		<meta name="author" content="" />

		<link rel="stylesheet" href="/assets/css/fonts/linecons/css/linecons.css">
		<link rel="stylesheet" href="/assets/css/fonts/fontawesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="/assets/css/bootstrap.css">
		<link rel="stylesheet" href="/assets/css/core.css?<?php echo time();?>">
		<link rel="stylesheet" href="/assets/css/forms.css">
		<link rel="stylesheet" href="/assets/css/components.css">
		<link rel="stylesheet" href="/assets/css/skins.css">
		<link rel="stylesheet" href="/assets/css/custom.css">
		<link rel="stylesheet" href="/assets/js/select2/select2.css">
		<link rel="stylesheet" href="/assets/js/select2/select2-bootstrap.css">

		<script src="/assets/js/jquery-1.11.1.min.js"></script>
		<script src="/assets/js/jquery.qrcode.min.js"></script>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="/assets/js/html5shiv.min.js"></script>
			<script src="/assets/js/respond.min.js"></script>
		<![endif]-->

			<!-- Imported styles on this page -->
		<link rel="stylesheet" href="/assets/css/fonts/meteocons/css/meteocons.css">
		<!-- Bottom Scripts -->
		<script src="/assets/js/bootstrap.min.js"></script>
		<script src="/assets/js/TweenMax.min.js"></script>
		<script src="/assets/js/resizeable.js"></script>
		<script src="/assets/js/joinable.js"></script>
		<script src="/assets/js/api.js"></script>
		<script src="/assets/js/toggles.js"></script>

		<!-- Imported scripts on this page -->
		<script src="/assets/js/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
		<script src="/assets/js/jvectormap/regions/jquery-jvectormap-world-mill-en.js"></script>
		<script src="/assets/js/widgets.js"></script>

		<!-- JavaScripts initializations and stuff -->
		<script src="/assets/js/custom.js"></script>
<!-- 		<script src="/assets/js/googleAnalytics.js"></script> -->
	</head>
	<body class="page-body">
		<?php /* echo $this->render('settings-panel.phtml') */ ?>
		<div class="page-container">
			<?php echo $this->render('left-nav.phtml') ?>
			<div class="main-content">
				<?php echo $this->render('title-nav.phtml') ?>
				<?php echo $this->layout()->content;?>
			</div>
		</div>

		<!-- Modal 4 (Confirm)-->
		<div class="modal fade" id="modal-4" data-backdrop="static">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">Confirm!</h4>
					</div>
					<div class="modal-body">
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-info" data-dismiss="modal">Continue</button>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>
<script src="/assets/js/form/m5common.js?<?php echo time();?>"></script>
 <script type="text/javascript" src ="/assets/js/form/bootbox.min.js"></script>
 <script src="/assets/js/select2/select2.min.js"></script>
 <script type="text/javascript">
	const current_url = '<?php echo 'http://'.$_SERVER['SERVER_NAME'].':'.$_SERVER['SERVER_PORT'];?>';
	<?php
		$PIN_COST_RQ = new CFG();
		if(Zend_Registry::isRegistered(SYS::SYS_PIN_COST)) {
			$PIN_COST_RQ->request_pin_cost = Zend_Registry::get(SYS::SYS_PIN_COST)->request_pin_cost;
		}

	?>
	const pin_cost = <?php echo $PIN_COST_RQ->request_pin_cost; ?>;
	const fee = <?php echo BLC::FEE; ?>;

	var iPad = /iPad/.test(navigator.userAgent) && !window.MSStream;
	var iPhone = /iPhone/.test(navigator.userAgent) && !window.MSStream;
	viewport = document.querySelector("meta[name=viewport]");
	if(iPad) {
		viewport.setAttribute('content', 'width=device-width, initial-scale=0.8, maximum-scale=1.0, user-scalable=1');
	}

	if(iPhone){
		viewport.setAttribute('content', 'width=device-width, initial-scale=0.3, maximum-scale=1.0, user-scalable=1');
	}
 </script>
