<nav class="navbar horizontal-menu navbar-fixed-top">
	<!-- set fixed position by adding class "navbar-fixed-top" -->
	<div class="navbar-inner">
		<!-- Navbar Brand -->
		<div class="navbar-brand">
			<a href="/" class="logo" style="font-size: 3vw;">
				<img height="60" alt="logo" src="/assets/images/logo5.png"/>
			</a>
		</div>
		<!-- Mobile Toggles Links -->
		<div class="nav navbar-mobile">
			<!-- This will toggle the mobile menu and will be visible only on mobile devices -->
			<div class="mobile-menu-toggle">
				<a href="#" data-toggle="mobile-menu-horizontal"> <i class="fa-bars"></i></a>
			</div>

		</div>
		<div class="navbar-mobile-clear"></div>
		<!-- main menu -->
		<ul class="navbar-nav">
			<li class="">
				<a href="/dashboard">
					<i class="linecons-desktop"></i>
					<span class="title">DASHBOARD</span>
				</a>
			</li>
			<li class="has-sub howitworks">
				<a href="/howitworks/en">
					<i class="linecons-cog"></i>
					<span class="title">HOW IT WORKS</span>
				</a>
				<ul>
					<li>
						<a href="/howitworks/vn">
							<span class="title">Việt Nam</span>
						</a>
					</li>
					<li>
						<a href="/howitworks/en">
							<span class="title">English</span>
						</a>
					</li>
				</ul>
			</li>
			<li class="">
				<a href="/register">
					<i class="linecons-user"></i>
					<span class="title">REGISTRATION</span>
				</a>
			</li>
			<li class="">
				<a href="/contact">
					<i class="fa-envelope-o"></i>
					<span class="title">CONTACT US</span>
				</a>
			</li>
		</ul>
		<ul class="navbar-nav pull-right">
			<li class="">
				<?php if($this->user['user_name'] ==''){?>
				<a href="/login">
					<img src="/assets/images/user-4.png" alt="user-image" class="img-circle img-inline userpic-32" width="28">
					<span class="title">LOGIN</span>
				</a>
				<?php }else{?>
				<li class="dropdown user-profile" style="min-height: 76px;">
					<a href="/logout">
						<i class="fa-edit"></i>
						Logout
					</a>
				</li>
				<?php }?>
			</li>
		</ul>
	</div>
</nav>