<nav class="navbar user-info-navbar" role="navigation">
	<!-- Left links for user info navbar -->
	<ul class="user-info-menu left-links list-inline list-unstyled">
		<li class="hidden-sm hidden-xs" style="min-height: 76px;">
			<a href="#" data-toggle="sidebar"> <i class="fa-bars"></i></a>
		</li>
	</ul>
	<!-- Right links for user info navbar -->
	<ul class="user-info-menu right-links list-inline list-unstyled">
		<li class="dropdown user-profile" style="min-height: 76px;">
			<a href="/">
				<i class="linecons-desktop"></i>
				<span>HOME</span>
			</a>
		</li>
	</ul>
</nav>