<section>
	<div class="section-body contain-lg">
		<section class="content-header">
			<h1 class="text-primary">
				Wallet <small>Overview</small>
			</h1>
		</section>
		<!-- Main content -->
		<div class="card">
			<div class="card-body">
				<section class="content">
					<div id="step2" class="form-group">
						<div style="display: block;">
							<h2 class="text-primary">YOU TRANSFER TO THIS WALLET ADDRESS:</h2>
							<a
								href="https://blockchain.info/address/<?php echo $this->data[0][0]['btc_address'];?>">
							</a>
						</div>
						<a
							href="https://blockchain.info/address/<?php echo $this->data[0][0]['btc_address'];?>">
							<br>
							<div id="qrcode" style="float: left" align="center">
								<canvas height="256" width="256"></canvas>
							</div>
							<div style="float: left; padding-left: 15px; width: 40%;text-align: left;"
								align="center">
								<span style="font-size: 20px">WITHDRAWABLE: </span><i
									style="font-size: 20px" class="fa fa-bitcoin orange"></i> <span
									class="orange" id="pin_total" style="font-size: 20px"><?php echo $this->data[0][0]['withdrawable']?></span>
							</div>
							<div style="float: left;padding-left: 15px;width: 40%; text-align: left;"
								align="center">
								<span style="font-size: 20px">BALANCE: </span><i
									style="font-size: 20px" class="fa fa-bitcoin orange"></i> <span
									class="orange" id="pin_total" style="font-size: 20px"><?php echo $this->data[0][0]['balance'];?></span>
							</div>

						</a>
						<div style="clear: both"></div>
						<p>
							<b>Wallet Links</b><br> <a target="_blank"
								href="https://blockchain.info/address/<?php echo $this->data[0][0]['btc_address'];?>">Blockchain</a>,
							<a target="_blank"
								href="https://blockexplorer.com/address/<?php echo $this->data[0][0]['btc_address'];?>">Blockexplorer</a>,
							<a target="_blank"
								href="https://chain.so/address/BTC/<?php echo $this->data[0][0]['btc_address'];?>">SoChain</a>
						</p>
						<div style="font-size: 16px; color: red; font-weight: bold"><?php echo $this->data[0][0]['btc_address'];?></div>
					</div>
				</section>
			</div>
			<div class="row">
				<div class="col-xs-6">
					<button type="button" id= "btn_update_wallet"  class="btn btn-turquoise">Update</button>
				</div>
			</div>
		</div>

	</div>
</section>

<script type="text/javascript">
$(document).ready(function($) {
	$('#btn_update_wallet').prop('disabled', false);
    $('#qrcode').qrcode("<?php echo $this->data[0][0]['btc_address'];?>");
    $('#btn_update_wallet').click(function(){
        $(this).prop('disabled', true);
    	location.reload();
    });
});
</script>