<!DOCTYPE html>
<html>
<head>
<title><?php echo  'BTCCLUB - ' . $this->title;?></title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="btcclub" />
	<meta name="author" content="" />

	<link rel="stylesheet" href="/assets/css/fonts/fontawesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="/assets/css/bootstrap_home.css">
	<link rel="stylesheet" href="/assets/css/custom.css">
	<link rel="stylesheet" href="/assets/css/home.css?<?php echo time();?>">


	<script src="/assets/js/jquery-1.11.1.min.js"></script>

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		<script src="/assets/js/html5shiv.min.js"></script>
		<script src="/assets/js/respond.min.js"></script>
	<![endif]-->
</head>
<?php $homeData = $this->homeData;?>
<body class="login-page login-light">
	<div class="wrapper">
		<div id="header">
			<div id="slider">
				<!-- use jssor.slider.mini.js (40KB) instead for release -->
				<!-- jssor.slider.mini.js = (jssor.js + jssor.slider.js) -->
				<script type="text/javascript" src="/assets/js/jssor.js" tppabs="/assets/js/jssor.js"></script>
				<script type="text/javascript" src="/assets/js/jssor.slider.js" tppabs="/assets/js/jssor.slider.js"></script>
				<script>

					jQuery(document).ready(function ($) {

						var _SlideshowTransitions = [
							//Fade
							{ $Duration: 1200, $Opacity: 2 }
						];

						var options = {
							$AutoPlay: true, //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
							$AutoPlaySteps: 1, //[Optional] Steps to go for each navigation request (this options applys only when slideshow disabled), the default value is 1
							$AutoPlayInterval: 3000, //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
							$PauseOnHover: 1, //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1

							$ArrowKeyNavigation: true, //[Optional] Allows keyboard (arrow key) navigation or not, default value is false
							$SlideDuration: 500, //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
							$MinDragOffsetToSlide: 20, //[Optional] Minimum drag offset to trigger slide , default value is 20
							//$SlideWidth: 600,                                 //[Optional] Width of every slide in pixels, default value is width of 'slides' container
							//$SlideHeight: 300,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container
							$SlideSpacing: 0, //[Optional] Space between each slide in pixels, default value is 0
							$DisplayPieces: 1, //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
							$ParkingPosition: 0, //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
							$UISearchMode: 1, //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
							$PlayOrientation: 1, //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1
							$DragOrientation: 3, //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)

							$SlideshowOptions: {//[Optional] Options to specify and enable slideshow or not
								$Class: $JssorSlideshowRunner$, //[Required] Class to create instance of slideshow
								$Transitions: _SlideshowTransitions, //[Required] An array of slideshow transitions to play slideshow
								$TransitionsOrder: 1, //[Optional] The way to choose transition to play slide, 1 Sequence, 0 Random
								$ShowLink: true                                    //[Optional] Whether to bring slide link on top of the slider when slideshow is running, default value is false
							},
							$BulletNavigatorOptions: {//[Optional] Options to specify and enable navigator or not
								$Class: $JssorBulletNavigator$, //[Required] Class to create navigator instance
								$ChanceToShow: 2, //[Required] 0 Never, 1 Mouse Over, 2 Always
								$AutoCenter: 1, //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
								$Steps: 1, //[Optional] Steps to go for each navigation request, default value is 1
								$Lanes: 1, //[Optional] Specify lanes to arrange items, default value is 1
								$SpacingX: 10, //[Optional] Horizontal space between each item in pixel, default value is 0
								$SpacingY: 10, //[Optional] Vertical space between each item in pixel, default value is 0
								$Orientation: 1                                 //[Optional] The orientation of the navigator, 1 horizontal, 2 vertical, default value is 1
							},
							$ArrowNavigatorOptions: {
								$Class: $JssorArrowNavigator$, //[Requried] Class to create arrow navigator instance
								$ChanceToShow: 2, //[Required] 0 Never, 1 Mouse Over, 2 Always
								$Steps: 1                                       //[Optional] Steps to go for each navigation request, default value is 1
							}
						};
						var jssor_slider1 = new $JssorSlider$("slider1_container", options);

						//responsive code begin
						//you can remove responsive code if you don't want the slider scales while window resizes
						function ScaleSlider() {
							var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
							if (parentWidth)
								jssor_slider1.$ScaleWidth(Math.min(parentWidth, 1000));
							else
								window.setTimeout(ScaleSlider, 30);
						}
						ScaleSlider();

						$(window).bind("load", ScaleSlider);
						$(window).bind("resize", ScaleSlider);
						$(window).bind("orientationchange", ScaleSlider);
						//responsive code end
					});
				</script>
				<!-- Jssor Slider Begin -->
				<!-- To move inline styles to css file/block, please specify a class name for each element. -->
				<div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 1000px; height: 400px; overflow: hidden;">

					<!-- Loading Screen -->
					<div u="loading" style="position: absolute; top: 0px; left: 0px;">
						<div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; background-color: #000000; top: 0px; left: 0px; width: 100%; height: 100%;">
						</div>
						<div style="position: absolute; display: block; background: url(loading.gif)/*tpa=/assets/images/home/loading.gif*/ no-repeat center center; top: 0px; left: 0px; width: 100%; height: 100%;">
						</div>
					</div>

					<!-- Slides Container -->
					<div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1000px; height: 400px; overflow: hidden;">
						<div>
							<img u="image" src="/assets/images/home/s1.jpg" tppabs="/assets/images/home/s1.jpg" />
						</div>
						<div>
						   <img u="image" src="/assets/images/home/s1.jpg" tppabs="/assets/images/home/s1.jpg" />
						</div>
						<div>
							<img u="image" src="/assets/images/home/s1.jpg" tppabs="/assets/images/home/s1.jpg" />
						</div>
						<div>
							<img u="image" src="/assets/images/home/s1.jpg" tppabs="/assets/images/home/s1.jpg" />
						</div>
						<div>
							<img u="image" src="/assets/images/home/s1.jpg" tppabs="/assets/images/home/s1.jpg" />
						</div>
					</div>

					<!--#region Bullet Navigator Skin Begin -->
					<!-- Help: http://www.jssor.com/development/slider-with-bullet-navigator-jquery.html -->
					<style>
						/* jssor slider bullet navigator skin 05 css */
						/*
						.jssorb05 div           (normal)
						.jssorb05 div:hover     (normal mouseover)
						.jssorb05 .av           (active)
						.jssorb05 .av:hover     (active mouseover)
						.jssorb05 .dn           (mousedown)
						*/
						.jssorb05 {
							position: absolute;
						}

							.jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
								position: absolute;
								/* size of bullet elment */
								width: 16px;
								height: 16px;
								background: url(b05.png)/*tpa=/assets/images/home/b05.png*/ no-repeat;
								overflow: hidden;
								cursor: pointer;
							}

							.jssorb05 div {
								background-position: -7px -7px;
							}

								.jssorb05 div:hover, .jssorb05 .av:hover {
									background-position: -37px -7px;
								}

							.jssorb05 .av {
								background-position: -67px -7px;
							}

							.jssorb05 .dn, .jssorb05 .dn:hover {
								background-position: -97px -7px;
							}
					</style>
					<!-- bullet navigator container -->
					<div u="navigator" class="jssorb05" style="bottom: 16px; right: 6px;">
						<!-- bullet navigator item prototype -->
						<div u="prototype"></div>
					</div>
					<!--#endregion Bullet Navigator Skin End -->

					<!--#region Arrow Navigator Skin Begin -->
					<!-- Help: http://www.jssor.com/development/slider-with-arrow-navigator-jquery.html -->
					<style>
						/* jssor slider arrow navigator skin 12 css */
						/*
						.jssora12l                  (normal)
						.jssora12r                  (normal)
						.jssora12l:hover            (normal mouseover)
						.jssora12r:hover            (normal mouseover)
						.jssora12l.jssora12ldn      (mousedown)
						.jssora12r.jssora12rdn      (mousedown)
						*/
						.jssora12l, .jssora12r {
							display: block;
							position: absolute;
							/* size of arrow element */
							width: 30px;
							height: 46px;
							cursor: pointer;
							background: url(<?php echo $this->baseUrl('/assets/images/home/a16.png')?>)/*tpa=/assets/images/home/a16.png*/ no-repeat;
							overflow: hidden;
						}

						.jssora12l {
							background-position: -16px -37px;
						}

						.jssora12r {
							background-position: -75px -37px;
						}

						.jssora12l:hover {
							background-position: -136px -37px;
						}

						.jssora12r:hover {
							background-position: -195px -37px;
						}

						.jssora12l.jssora12ldn {
							background-position: -256px -37px;
						}

						.jssora12r.jssora12rdn {
							background-position: -315px -37px;
						}
					</style>
					<!-- Arrow Left -->
					<span u="arrowleft" class="jssora12l" style="top: 123px; left: 0px;"></span>
					<!-- Arrow Right -->
					<span u="arrowright" class="jssora12r" style="top: 123px; right: 0px;"></span>
				</div>
				<!-- Jssor Slider End -->
			</div>
			<div id="menu">
				<div id="logo"><a href="#">
					<img src="<?php echo $this->baseURL('/assets/images/home/Logo_BTC.PNG');?>" tppabs="/assets/images/home/Logo_BTC.PNG" style="width: 75px"></a></div>
				<div id="menubar">
					<ul>
						<?php if(!empty($this->user['user_name'])){?>
						<li><a href="/dashboard">
							<img src="<?php echo $this->baseURL('/assets/images/home/icon.png');?>" tppabs="/assets/images/home/icon.png">DASHBOARD</a></li>
							<?php }?>
						<li><a href="/howitworks/en">
							<img src="<?php echo $this->baseURL('/assets/images/home/icon.png');?>" tppabs="/assets/images/home/icon.png">HOW IT WORKS</a></li>
						<li><a href="/register">
							<img src="<?php echo $this->baseURL('/assets/images/home/icon.png');?>" tppabs="/assets/images/home/icon.png">RESGISTRATION</a></li>
						<li><a href="/contact">
							<img src="<?php echo $this->baseURL('/assets/images/home/icon.png');?>" tppabs="/assets/images/home/icon.png">CONTACT US</a></li>
					</ul>
				</div>
				<div id="login-btn">
				<?php if($this->user['user_name'] ==''){?>
					<a class='logined' href="javascript:void(0)"><img src="<?php echo $this->baseURL('/assets/images/home/icon.png');?>" tppabs="/assets/images/home/icon.png">Login</a>
				<?php }else{?>
					<a href="/logout"><img src="<?php echo $this->baseURL('/assets/images/home/icon.png');?>" tppabs="/assets/images/home/icon.png">Logout</a>
				<?php }?>
				</div>
			</div>
		</div>
		<div id="content">

			<div class="main_content">
				<div class="title_content bgabout">
					<div class="img">
						<div class="title"><?php echo $homeData[0]['title'];?></div>
					</div>
				</div>
				<div class="detail_content">
					<div id="image_content">
						<img width="250" height="160" src="<?php echo $this->baseURL('/assets/images/home/about.jpg');?>" tppabs="/assets/images/home/about.jpg">
					</div>
					<div id="artile">
						<?php echo html_entity_decode($homeData[0]['content']);?>
					</div>
				</div>
			</div>

			<?php echo $this->layout()->content;?>

			<div class="main_content pack3">
				<div class="title_content">
					<div class="img">
						<div class="title">Engagement</div>
					</div>
				</div>
				<div class="detail_content">
					<div class="contenck">
					<div class="camket">
						<div class="title">
							<h3><img src="<?php echo $this->baseURL('/assets/images/home/cs.png');?>" tppabs="/assets/images/home/cs.png" alt="cs" />
							<?php echo $homeData[13]['title'];?>
							</h3>
						</div>
						<div class="content">
							<?php echo html_entity_decode($homeData[13]['content']);?>
						</div>
					</div>
					<div class="camket">
						<div class="title">
							<h3><img src="<?php echo $this->baseURL('/assets/images/home/dk.png');?>" tppabs="/assets/images/home/dk.png" alt="dk"/>
							<?php echo $homeData[14]['title'];?>
							</h3>
						</div>
						<div class="content">
							<?php echo html_entity_decode($homeData[14]['content']);?>
						</div>
					</div>
					</div>
				</div>
			</div>
		</div>
		<div id="footer">
			<div id="doitac">
				<div class="content">
<a href="#"><img style="width: 100%;" src="/assets/images/home/dt.png" tppabs="/assets/images/home/dt.png" alt="dt"/></a>
					</div>
			</div>
			<div id="footermenu">
				<ul>
					<li><a href="#">HOME</a></li>
					<li><a href="#">HOW IT WORKS</a></li>
					<li><a href="#">CONTACT US</a></li>
					</ul>
			</div>
			<div id="bootom_footer">
				<div class="copy">Copyright © 2016 BTCCLUB   |   All Rights Reserved</div>
				<div class="mxh"><a href="#"><img src="<?php echo $this->baseURL('/assets/images/home/mxh.png');?>" tppabs="/assets/images/home/mxh.png" alt="mxh"></a></div>
			</div>
		</div>
	</div>


	<div class="login-container">
		<div class="col-xs-12 login-content" >
			<!-- Errors container -->
			<div class="errors-container"></div>
			<!-- Add class "fade-in-effect" for login form effect -->
			<form method="post" role="form" id="login"
				class="login-form fade-in-effect">
				<img id="login-close" height="25" src="/assets/images/remove.svg" />
				<div class="login-logo text-center">
					<img style="width: auto;max-height: 150px;max-width: 100%;" alt="logio" src="/assets/images/logo.png">
				</div>
				<div class="login-header">
					<p>Login</p>
				</div>
				<div class="form-group">
					<input type="text" class="form-control required" data-validate="required" data-message-required="This is required field." name="Username" placeholder="Username or email" id="username" />
				</div>
				<div class="form-group">
					<input type="password" class="form-control required" data-validate="required" data-message-required="This is required field." name="passwd" id="passwd"
						placeholder="Password" />
				</div>
				<div class="form-group">
					<label class="captcha">Please type word: <?php echo $this->captcha;?>  </label>
					<input autocomplete="off" autofocus="autofocus" autocorrect="off" autocapitalize="none" type="text" class="form-control required" data-validate="required" data-message-required="This is required field." name="passwd" id="captcha"
						placeholder="captcha" />
				</div>
				<div class="form-group">
					<button id="btn-login" type="button" class="btn btn-primary  btn-block text-left" captcha="<?php echo $this->captcha;?>">
						<i class="fa-lock"></i> SIGN IN
					</button>
				</div>
				<div class="login-footer">
					<a href="/resetpassword">Forgot your password?</a>
				</div>
			</form>
		</div>
	</div>

	<!-- Modal 4 (Confirm)-->
	<div class="modal fade" id="modal-4" data-backdrop="static">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">Confirm!</h4>
				</div>
				<div class="modal-body">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-info" data-dismiss="modal">Continue</button>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

<script src="/assets/js/form/m5common.js?<?php echo time();?>"></script>
<script src="/assets/js/form/login.js?<?php echo time();?>"></script>

<script type="text/javascript">
	var iPad = /iPad/.test(navigator.userAgent) && !window.MSStream;
	var iPhone = /iPhone/.test(navigator.userAgent) && !window.MSStream;
	viewport = document.querySelector("meta[name=viewport]");
	if(iPad) {
		viewport.setAttribute('content', 'width=device-width, initial-scale=0.7, maximum-scale=1.0, user-scalable=1');
// 		$('img.laixuat').css('height','220px');
// 		$('ul.list-video ').find('img').css({'height':'175px', 'vertical-align': 'bottom'});
// 		$('ul.list-video ').find('iframe').css({'height':'175px'});
	}

	if(iPhone){
		viewport.setAttribute('content', 'width=device-width, initial-scale=0.3, maximum-scale=1.0, user-scalable=1');
// 		$('img.laixuat').css('height','220px');
// 		$('ul.list-video ').find('img').css({'height':'175px', 'vertical-align': 'bottom'});
// 		$('ul.list-video ').find('iframe').css({'height':'175px'});
	}
 </script>