<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Setting User</h3>
		</div>
		<div class="panel-body">
			<div id="example-2_wrapper"
				class="dataTables_wrapper form-inline dt-bootstrap no-footer">
				<table class="table table-bordered table-striped dataTable no-footer"
					role="grid" aria-describedby="example-2_info">
					<thead>
						<tr role="row">
							<th>No</th>
							<th>User Name</th>
							<th>Email</th>
							<th>Status</th>
							<th></th>
						</tr>
					</thead>
					<tbody class="middle-align">
						<?php foreach ($this->data as $index => $row) {?>
						<tr role="row">
							<td>
								<?php echo ++$index;?>
							</td>
							<td><?php echo $row['user_name'];?></td>
							<td><?php echo $row['email'];?></td>
							<td><?php echo $row['status_name'];?></td>
							<td>
								<button user_id="<?php echo $row['user_id'];?>" status="<?php echo $row['status'] == 1 ? 2: 1;?>" type="button"  class="btn btn-turquoise btn-save-user">
								<?php echo $row['status'] == 1 ? 'freeze'  : 'unfreeze';  ?>
								</button>
							</td>
						</tr>
						<?php }?>

					</tbody>
				</table>
			</div>
		</div>
	</div>
