<style>
.name-error {
	display: block;
}
</style>
<script src="assets/js/form/admin.js?<?php echo time();?>"></script>
<div id="admin-content">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Setting Rate</h3>
		</div>
		<div class="panel-body">
			<div id="example-2_wrapper"
				class="dataTables_wrapper form-inline dt-bootstrap no-footer">
				<table class="table table-bordered table-striped dataTable no-footer"
					role="grid" aria-describedby="example-2_info">
					<thead>
						<tr role="row">
							<th>No</th>
							<th>Name</th>
							<th>Value</th>
							<th></th>
						</tr>
					</thead>
					<tbody class="middle-align">
						<?php foreach ($this->data as $index => $row) {?>
						<tr role="row">
							<td>
								<?php echo ++$index;?>
							</td>
							<td><?php echo $row['sys_name'];?></td>
							<td>
								<div class="form-group" style="width: 100%;">
									<input style="width: 100%;" name="<?php echo $row['sys_name'];?>" type="text" value="<?php echo $row['sys_value'];?>" ></input>
								</div>
							</td>

							<td><button type="button"  class="btn btn-turquoise btn-save-rate">Save</button></td>
						</tr>
						<?php }?>

					</tbody>
				</table>
			</div>
		</div>
	</div>


</div>