<link rel="stylesheet" href="assets/js/dropzone/css/dropzone.css">
<link rel="stylesheet" href="assets/js/wysihtml5/src/bootstrap-wysihtml5.css">
<style>
.name-error {
	display: block;
}
</style>

<div id="admin-content">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Settings home page</h3>
		</div>
		<div class="panel-body">
		<form class="" enctype="multipart/form-data" id="form_setting" img="<?php echo $this->homedata[0]['img_path'];?>">
			<input name="id" type="hidden" id='st-id' value="<?php echo $this->homedata[0]['id']?>" />
			<div class="form-group col-xs-12">
				<label class="col-xs-3 control-label required" for="field-1">Chose change:</label>
				<div class="col-xs-6">
					<select class="form-control required" id="setting_home">
						<?php foreach ($this->homedata as $type) {?>
							<option
							data-id="<?php echo $type['id'];?>"
							value="<?php echo $type['id'];?>">
								<?php echo $type['type'];?>
							</option>
						<?php }?>
					</select>
				</div>
			</div>

			<div class="form-group col-xs-12">
				<label class="col-xs-12 control-label required" for="">TITLE</label>
				<input id='st-title' name="title" class="form-control st" value="<?php echo $this->homedata[0]['title'];?>" />
			</div>
			<div class="form-group col-xs-12">
				<label class="col-xs-12 control-label required" for="">Banner</label>
				<div class="" id = "picture">
					<img id='st-img' name="img" class="form-control st" style="height: auto;max-height: 200px; width: auto;" alt="" src="<?php echo $this->homedata[0]['img_path'];?>" />
					<input type="hidden" name="img_path" id='st-img-path' value="<?php echo $this->homedata[0]['img_path'];?>" />
					<input type="file" class="" id="upload-img"  name="profile">
				</div>
				<div class="clearfix"></div>
			</div>

			<div class="form-group col-xs-12">
				<label class="col-xs-12 control-label required" for="">Link</label>
				<input id="link" name="link" class="form-control st" value="<?php echo $this->homedata[0]['link'];?>" placeholder="link" />
			</div>
			<div class="form-group col-xs-12">
				<label class="col-xs-12 control-label required" for="">Content</label>
				<textarea id="text-content" name="content" class="form-control wysihtml5 st" data-stylesheet-url="assets/js/wysihtml5/lib/css/wysiwyg-color.css" name="sample_wysiwyg" id="sample_wysiwyg">
					<?php echo html_entity_decode($this->homedata[0]['content']);?>
				</textarea>
			</div>
		</div>
		</form>
		<div class="form-group col-xs-12">
			<button id="btn-save" type="button" class="btn btn-turquoise btn-save-rate">Save</button>
		</div>
		<div class="clearfix"></div>
	</div>
</div>



<script type="text/javascript">
	var dataSetting = <?php echo json_encode($this->homedata);?>;
// 	console.log(dataSetting);
	$(document).on('change','#upload-img',function(){
		try{
			var data	=	new FormData();
			var _this	=	this;
			data.append('fileUpload', $("#upload-img")[0].files[0]);
			$.ajax({
				url			:	"/master/home/uploadimg",
				type		:	"POST",
				dataType	:	"json",
				data		:	data,
				enctype		:	'multipart/form-data',
				loading		:	true,
				processData	:	false,
				contentType	:	false
				}).done(function(data) {
					switch(data.status){
						case '1':
							$( "#st-img-path" ).val(data.path);
// 							$('#picture').find('input').hide();
							$('#picture').find('img').attr('src',data.path ).show();
							break;
						default:
							alert('Upload file error!');
					}
			});
		}catch(e){
			alert('upload file: '+e.message);
		}
	});

</script>

<script src="assets/js/wysihtml5/lib/js/wysihtml5-0.3.0.js"></script>
<script src="assets/js/wysihtml5/src/bootstrap-wysihtml5.js"></script>
<script src="assets/js/dropzone/dropzone.min.js"></script>
<script src="assets/js/form/admin.js?<?php echo time();?>"></script>