<object data="/<?php echo $this->lang;?>.pdf" type="application/pdf" width="100%" height="768px">
  <p>Alternative text - include a link <a href="/<?php echo $this->lang;?>.pdf">to the PDF!</a></p>
</object>
 <script type="text/javascript">

	var iOS = /iPad|iPhone/.test(navigator.userAgent) && !window.MSStream;

	if(iOS){
		$('object a').trigger('click');
		window.location = '/<?php echo $this->lang;?>.pdf';
	}
 </script>