<div class="main_content">
	<div id="register" class="">
		<div class="panel panel-default" style="height: auto;overflow: hidden;">
			<div class="panel-heading">
				<h3 class="panel-title">Account Information</h3>
				<div class="panel-options">
					<a href="#" data-toggle="panel"> <span class="collapse-icon"></span>
						<span class="expand-icon"></span>
					</a>
				</div>
			</div>
			<div class="panel-body">
				<form id="form-register" class="form-horizontal" >
					<div class="form-group">
						<label class="col-xs-3 control-label" for="field-1">Username</label>
						<div class="col-xs-9">
							<input type="text" class="form-control" id="username" name="user_name" >
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-3 control-label" for="field-1">Upline Username</label>
						<div class="col-xs-9">
							<input <?php if(!empty($this->parent_name)) {echo 'readonly="readonly"';}?> type="text" class="form-control" id="parent_name" name="parent_name" value="<?php echo $this->parent_name ?>" />
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-3 control-label" for="field-1">Wallet address</label>
						<div class="col-xs-9">
							<input type="text" class="form-control" id="wallet" name="wallet" >
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-3 control-label" for="field-1">Password</label>
						<div class="col-xs-9">
							<input type="password" class="form-control" id="password" name="password" >
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-3 control-label" for="field-1">Confirm Password</label>
						<div class="col-xs-9">
							<input type="password" class="form-control" id="confirmpassword" name="confirm_pwd"  />
						</div>
					</div>

<!-- 					<div class="form-group"> -->
<!-- 						<label class="col-xs-3 control-label" for="field-1">Security Password</label> -->
<!-- 						<div class="col-xs-9"> -->
<!-- 							<input type="password" class="form-control" id="securitypassword" name="t_password"> -->
<!-- 						</div> -->
<!-- 					</div> -->
<!-- 					<div class="form-group"> -->
<!-- 						<label class="col-xs-3 control-label" for="field-1">Confirm Security Password</label> -->
<!-- 						<div class="col-xs-9"> -->
<!-- 							<input type="password" class="form-control" id="confirmsecuritypassword" name="t_password_2"> -->
<!-- 						</div> -->
<!-- 					</div> -->

					<div class="form-group-separator"></div>
					<div class="form-group">
						<label class="col-xs-3 control-label" for="field-1">Personal Name</label>
						<div class="col-xs-9">
							<input type="text" class="form-control" id="personalname" name="full_name" />
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-3 control-label" for="field-1">Personal Email</label>
						<div class="col-xs-9">
							<input type="email" class="form-control" id="email" name="email" />
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-3 control-label" for="field-1">Personal Mobile</label>
						<div class="col-xs-9">
							<input type="text" class="form-control" id="mobile" name="mobile" />
						</div>
					</div>
					<div class="form-group-separator"></div>
				</form>
				<div class="form-group" style="text-align: center;padding-top:10px;">
					<button  id="btn-save" class="btn btn-info">Register Now</button>
					<button id="btn-cancel" class="btn btn-red">Cancel</button>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="/assets/js/form/register.js?<?php echo time();?>"></script>