<?php foreach ($this->arrnews as $row){?>
<div class="row">
	<div class="mail-single-info">
		<div class="mail-single-info-user dropdown">
			<a href="#" data-toggle="dropdown">
				<span style="color: blue;font-size:18px"><?php echo $row['title'];?></span>
				<?php $date = new DateTime($row['create_date']);?>
				<em class="time" style="color:#ea2e2b;"><?php echo date_format($date, 'd-m-Y H:i:s');?></em>
			</a>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-3">
		<img src="<?php echo $row['image'];?>" style="width:100%;"/>
	</div>
	<div class="mail-single-body col-xs-9" style="border-bottom: none;padding-bottom: 0px;">
		<p><?php echo $row['description'];?></p>
	</div>
	<div class="mail-single-info">
		<div class="mail-single-info-options">
			<a href="#" class="star starred"> <i class="fa-star-empty"></i></a>
		</div>
	</div>
</div>
<?php }?>
<div class="row">
	<div class="col-xs-12">
		<div class="dataTables_paginate paging_simple_numbers pull-right"
			id="example-2_paginate">
			<?php echo $this->paging;?>
		</div>
	</div>
</div>