<div class="main_content pack1">
<div id="contact" class="">
	<div class="panel panel-default" style="overflow: hidden;">
		<div class="panel-heading">
			<h3 class="panel-title">Contact us</h3>
			<div class="panel-options">
				<a href="#" data-toggle="panel"> <span class="collapse-icon"></span>
					<span class="expand-icon"></span>
				</a>
			</div>
		</div>
		<div class="panel-body">
			<div role="form" class="form-horizontal">
				<div class="form-group">
					<label class="col-xs-3 control-label" for="title">Name</label>
					<div class="col-xs-9">
						<input type="text" value="" class="form-control required">
					</div>
				</div>
				<div class="form-group">
					<label class="col-xs-3 control-label" for="title">Email</label>
					<div class="col-xs-9">
						<input type="text" value="" class="form-control required">
					</div>
				</div>
				<div class="form-group">
					<label class="col-xs-3 control-label" for="title">Telephone</label>
					<div class="col-xs-9">
						<input type="text" value="" class="form-control required">
					</div>
				</div>
				<div class="form-group">
					<label class="col-xs-3 control-label" for="description">Message</label>
					<div class="col-xs-9">
						<textarea class="form-control required" cols="5" rows="10" ></textarea>
					</div>
				</div>
				<div class="form-group" style="text-align: center">
					<button id="btn-submit" class="btn btn-info">Submit</button>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
<script type="text/javascript" src="/assets/js/form/contact.js?<?php echo time();?>"></script>