<?php $helper = $this->getHelper('MasterHelper');?>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">List message</h3>
		<div class="panel-options">
			<a href="/master/message/create"><button class="btn btn-red">New message</button></a>
		</div>
	</div>
	<div class="panel-body">
		<div id="example-2_wrapper"
			class="dataTables_wrapper form-inline dt-bootstrap no-footer">
			<div class="row">
				<div class="col-xs-6"></div>
				<div class="col-xs-6">
					<div id="example-1_filter" class="dataTables_filter pull-right">
						<label>Search:<input id="txt-search" type="search" class="form-control input-sm"
							placeholder="" aria-controls="example-1"></label>
					</div>
				</div>
			</div>
			<div id="display-result">
				<table class="table table-bordered table-striped dataTable no-footer" id="example-2" role="grid" aria-describedby="example-2_info">
					<thead>
						<tr role="row">
							<th style="width:50px">No</th>
							<th style="width:150px">From</th>
							<th>Content</th>
							<th style="width:150px">Status</th>
						</tr>
					</thead>
					<tbody class="middle-align">
						<?php foreach ($this->arrmsg as $key => $row){?>
						<tr role="row">
							<td><?php echo $key+1;?></td>
							<td><?php echo $row['user_name'];?></td>
							<td><a href="<?php echo $this->url(array('module'=>'master', 'controller'=>'Message', 'action'=>'msgview', 'id' => $row['msg_id']), null, true); ?>"><?php echo $row['msg_content'];?></a></td>
							<td><?php echo $helper->showStatusMSG($this->user['user_id'],$row['status'], $row['user_read'] );?></td>
						</tr>
						<?php }?>
					</tbody>
				</table>
				<div class="row">
					<div class="col-xs-12">
						<div class="dataTables_paginate paging_simple_numbers pull-right"
							id="example-2_paginate">
							<?php echo $this->paging;?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/assets/js/form/message.js?<?php echo time();?>"></script>