<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="btcclub" />
<meta name="author" content="" />
<title>BTCCLUB - <?php echo $this->title;?></title>
<link rel="stylesheet"
	href="http://fonts.googleapis.com/css?family=Arimo:400,700,400italic">
<link rel="stylesheet"
	href="/assets/css/fonts/fontawesome/css/font-awesome.min.css">
<link rel="stylesheet" href="/assets/css/bootstrap.css">
<link rel="stylesheet" href="/assets/css/core.css">
<link rel="stylesheet" href="/assets/css/forms.css">
<link rel="stylesheet" href="/assets/css/components.css">
<link rel="stylesheet" href="/assets/css/skins.css">
<script src="/assets/js/jquery-1.11.1.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
		<script src="/assets/js/html5shiv.min.js"></script>
		<script src="/assets/js/respond.min.js"></script>
	<![endif]-->
<style type="text/css">
.login-page.login-light {
	background-image: url("/assets/images/web_btcclub_login.jpg");
}

.login-page.login-light .login-form {
	/* 	background-color: #bf8f4c; */
	background-color: rgba(228, 194, 76, 0.4);
	border-radius: 6px;
	border: 1px solid black;
}

.login-page .login-form .login-header {
	margin-bottom: 10px;
}

.login-page .login-form .login-header p {
	color: white;
	font-size: 20px;
}

.btn.text-left, .login-header {
	text-align: center;
}

.login-page.login-light .login-form .login-footer a {
	color: white;
}
</style>
</head>
<body class="page-body login-page login-light">
	<div class="login-container">
		<div class="col-xs-6 login-content">
			<!-- Errors container -->
			<div class="errors-container"></div>
			<!-- Add class "fade-in-effect" for login form effect -->
			<form method="post" role="form" id="reset"
				class="login-form fade-in-effect">
				<div class="login-logo">
					<img alt="logio" src="/assets/images/logo.png">
				</div>
				<div class="login-header">
					<p>Change Password</p>
				</div>
				<div class="form-group">
					<input type="password" class="form-control required"
						data-validate="required"
						data-message-required="This is required field." name="password"
						placeholder="New Password" id="password" />
				</div>
				<div class="form-group">
					<input type="password" class="form-control required"
						data-validate="required"
						data-message-required="This is required field." name="password2"
						placeholder="Confirm Password" id="password2" />
				</div>
				<div class="form-group">
					<input type="text" class="form-control required"
						data-validate="required"
						data-message-required="This is required field." name="reset_code"
						placeholder="code" id="reset_code" />
				</div>
				<div class="form-group">
					<button id="btn-change-password" type="button"
						class="btn btn-primary  btn-block text-left">Change Password</button>
				</div>

			</form>
		</div>
	</div>

	<!-- Modal 4 (Confirm)-->
	<div class="modal fade" id="modal-4" data-backdrop="static">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">Confirm!</h4>
				</div>
				<div class="modal-body">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-info" data-dismiss="modal">Continue</button>
				</div>
			</div>
		</div>
	</div>
</body>
<!-- 	<script src="/assets/js/jquery-validate/jquery.validate.min.js"></script> -->
<script src="/assets/js/form/m5common.js?<?php echo time();?>"></script>
<script src="/assets/js/form/reset.js?<?php echo time();?>"></script>
</html>