<div class="tab-pane" id="invite">
	<div class="form-horizontal" method="post" novalidate="novalidate">
		<div class="col-xs-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2>Link Share</h2>
				</div>
				<div class="panel-body">
					<div class="control-group form-group">
						<div class="controls form-group">
							<label class="col-xs-3 control-label" for="BankName">Link</label>
							<div class="col-xs-9">
								<input class="form-control" type="text" id="bank_name"
									value="<?php echo $this->serverUrl() . $this->share;?>">
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>