<?php $profile = $this->profile;?>
<style>
input::-webkit-input-placeholder { /* Chrome/Opera/Safari */
  color: pink;
}
input::-moz-placeholder { /* Firefox 19+ */
  color: pink;
}
input:-ms-input-placeholder { /* IE 10+ */
  color: pink;
}
input:-moz-placeholder { /* Firefox 18- */
  color: pink;
}
</style>
<input type="hidden" value="<?php echo isset($profile['user_id'])?$profile['user_id']:'';?>" id="user_id"/>
<div class="search-results">
	<div class="tabs-vertical-env">
		<ul class="nav tabs-vertical">
			<li class="active"><a href="#account" data-toggle="tab"> <i
					class="fa-globe visible-xs"></i> <span class="hidden-xs">Account</span>
			</a></li>
			<li class=""><a href="#login" data-toggle="tab"> <i
					class="fa-picture visible-xs"></i> <span class="hidden-xs">Login Password</span>
			</a></li>
			<li style="display: none;" class=""><a href="#transaction" data-toggle="tab"> <i
					class="fa-docs visible-xs"></i> <span class="hidden-xs">Transaction password</span>
			</a></li>
			<li class=""><a href="#invite" data-toggle="tab">
			<i class="fa-video visible-xs"></i> <span class="hidden-xs">Invite +</span>
			</a></li>
		</ul>
		<div class="tab-content">
			<!-- Sample Search Results Tab -->
			<div class="tab-pane active" id="account">
				<div class="form-horizontal" method="post" novalidate="novalidate">
					<div class="col-xs-12">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h2>Account</h2>
							</div>
							<div class="panel-body">
								<div class="control-group form-group">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="UserName">UserName</label>
										<div class="col-xs-9">
											<input class="form-control"  readonly="readonly" type="text" id="user_name"
												value="<?php echo $profile['user_name'];?>">
										</div>
									</div>
								</div>

								<div class="control-group form-group">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="Email">Email</label>
										<div class="col-xs-9">
											<input readonly="readonly" class="form-control" type="text" id="email"
												value="<?php echo $profile['email'];?>">
										</div>
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="wallet">Wallet</label>
										<div class="col-xs-9">
											<input readonly="readonly" class="form-control" type="text" id="wallet"
												value="<?php echo $profile['wallet'];?>">
										</div>
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="Phone">Phone number</label>
										<div class="col-xs-9">
											<input readonly="readonly" class="form-control" type="text" id="phone"
												value="<?php echo $profile['phone'];?>">
										</div>
									</div>
								</div>
								<div class="control-group form-group hidden">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="code">Code</label>
										<div class="col-xs-9">
											<input class="form-control" type="text" id="code"  placeholder="" />
											<span style="color: red">Code from email</span>
										</div>
									</div>
								</div>
								<div >
									<div class="row">
										<div class="col-xs-12">
											<div id="success"></div>
										</div>
										<div class="col-xs-12" style="text-align: center;">
											<div class="btn-toolbar">
												<button id="btn-change" class="btn btn-primary">Change</button>
											</div>
											<div class="btn-toolbar hidden">
												<button id="btn-update-account" class="btn btn-primary">Update</button>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Search Results Tab -->
			<div class="tab-pane" id="login">
				<div  class="form-horizontal" method="post" novalidate="novalidate">
					<div class="col-xs-12">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h2>Password</h2>
							</div>
							<div class="panel-body">
								<div class="control-group form-group">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="OldPassword">Old Password</label>
										<div class="col-xs-9">
											<input class="form-control" id="old_password" type="password" />
										</div>
									</div>
								</div>

								<div class="control-group form-group">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="Password">New Password</label>
										<div class="col-xs-9">
											<input class="form-control" id="new_password" type="password" />
										</div>
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="ConfirmPassword">Confirm New Password</label>
										<div class="col-xs-9">
											<input class="form-control" id="confirm_password" type="password" />
										</div>
									</div>
								</div>
								<div class="">
									<div class="row">
										<div class="col-xs-12">
											<div id="success"></div>
										</div>
										<div class="col-xs-12" style="text-align: center;">
											<div class="btn-toolbar">
												<button id="changepassword" class="btn btn-primary">Update</button>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Search Results Tab -->
			<div class="tab-pane" id="transaction">
				<div class="form-horizontal" method="post" novalidate="novalidate">
					<div class="col-xs-12">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h2>Password</h2>
							</div>
							<div class="panel-body">
								<div class="control-group form-group">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="OldPassword">Old Password</label>
										<div class="col-xs-9">
											<input class="form-control" id="t_old_password" type="password" />
										</div>
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="Password">New Password</label>
										<div class="col-xs-9">
											<input class="form-control" id="t_new_password" type="password" />
										</div>
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="ConfirmPassword">Confirm Password</label>
										<div class="col-xs-9">
											<input class="form-control" id="t_confirm_password" type="password" />
										</div>
									</div>
								</div>
								<div class="">
									<div class="row">
										<div class="col-xs-12">
											<div id="success"></div>
										</div>
										<div class="col-xs-12" style="text-align: center;">
											<div class="btn-toolbar">
												<button id="change_t_password" class="btn btn-primary">Change Password</button>
												<a href="/auth/resetpassword" onclick="return confirm('Do you want to Reset Transaction Password?')"
													class="btn btn-danger">Reset Transaction Password</a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Search Results Tab -->
			<div class="tab-pane" id="invite">
				<div class="form-horizontal" method="post" novalidate="novalidate">
					<div class="col-xs-12">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h2>Link Share</h2>
							</div>
							<div class="panel-body">
								<div class="control-group form-group">
									<div class="controls form-group">
										<label class="col-xs-3 control-label" for="BankName">Link</label>
										<div class="col-xs-9">
											<input class="form-control" type="text" id="bank_name"
												value="<?php echo $this->serverUrl() . $this->share;?>">
										</div>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="/assets/js/form/profile.js?<?php echo time();?>"></script>